### ISSUE TITLE
かけらについて最終ページについて

### ISSUE THREAD

**Issue by harumidiv** [kokiTakashiki/omokake#5]
## 概要
* 最後のクレジットページから閉じるボタンがないのでユーザインタラクション的に使いにくい
* 13からスワイプダウンで閉じれるようになったのでそちらから閉じる場合も考慮すると1枚のVCで遷移させて一回で閉じられた方が良いかも

**Comment by kokiTakashiki** [comment]
ヘルプ画面をスクロールビューに集約しました。
クローズします。
